export const LIBRARY_LOADED='LOAD_LIBRARY';
export const DATA_LOADED='DATA_LOADED';
export const OPERATION_STARTED='OPERATION_STARTED';
export const OPERATION_COMPLETE='OPERATION_COMPLETE';
export const OPERATION_ERRORED='OPERATION_ERRORED';
