export const SEQUENCER_NAMES_LOADED = 'SEQUENCER_NAMES_LOADED';
export const SEQUENCER_COMMANDS_LOADED = 'SEQUENCER_CMDS_LOADED';
export const SEQUENCER_PREVIEW_LOADED = 'SEQUENCER_PREVIEW_LOADED';
export const SEQUENCER_EVAL_SUCCESS = 'SEQUENCER_EVAL_SUCCESS';
export const SEQUENCER_ERROR = 'SEQUENCER_ERROR';
export const SEQUENCER_ERROR_CLEARED = 'SEQUENCER_ERROR_CLEARED';
