FROM microsoft/dotnet:2.2-aspnetcore-runtime AS base
WORKDIR /app
EXPOSE  80

FROM microsoft/dotnet:2.2-sdk AS build
WORKDIR /src
COPY ["Host/TimeseriesAPI.csproj", "Host/"]
RUN dotnet restore "Host/TimeseriesAPI.csproj"
COPY . .
WORKDIR "/src/Host"
RUN dotnet build "TimeseriesAPI.csproj" -c Release -o /app

FROM build AS publish
RUN dotnet publish "TimeseriesAPI.csproj" -c Release -o /app

FROM base AS final
WORKDIR /app
COPY --from=publish /app .
ENTRYPOINT ["dotnet", "Timeseries.Api.dll"]
